.\" -*- nroff -*-
.\"
.TH IBV_EXP_MODIFY_WQ 3 2015-08-04 libibverbs "Libibverbs Programmer's Manual"
.SH "NAME"
ibv_exp_modify_wq \- Modify a Work Queue (WQ).
.SH "SYNOPSIS"
.nf
.B #include <infiniband/verbs_exp.h>
.sp
.BI "struct int ibv_exp_modify_wq(struct ibv_exp_wq " "*wq,"
.BI "                             struct ibv_exp_wq_attr " "*wq_attr" );
.sp
.fi
.SH "DESCRIPTION"
.B ibv_exp_modify_wq()
modifys a WQ
.I wq\fR.
The argument
.I wq_attr
is an ibv_exp_wq_attr struct, as defined in <infiniband/verbs_exp.h>.
.PP
.nf
struct ibv_exp_wq_attr {
.in +8
uint32_t                attr_mask;     /* Use enum ibv_exp_wq_attr_mask */
enum ibv_exp_wq_state   wq_state;      /* Move to this state */
enum ibv_exp_wq_state   curr_wq_state; /* Assume this is the current state */
uint16_t                vlan_offloads; /* Change WQ's VLAN offloading behaviour */
.in -8
};
.fi
.PP
The function
.B ibv_exp_modify_wq()
will modify the WQ based on the given
.I wq_attr\fB\fR->attr_mask
.SH "RETURN VALUE"
returns 0 on success, or the value of errno on failure (which indicates the failure reason).
.SH "SEE ALSO"
.BR ibv_exp_create_wq (3),
.BR ibv_exp_destroy_wq (3),
.SH "AUTHORS"
.TP
Yishai Hadas <yishaih@mellanox.com>
.TP
Noa Osherovich <noaos@mellanox.com>
