.TH IBV_EXP_CREATE_RES_DOMAIN 3 2015-05-25 libibverbs "Libibverbs Programmer's Manual"
.SH "NAME"
ibv_exp_create_res_domain \- create resource domain
.PP
ibv_exp_destroy_res_domain \- destroy resource domain
.SH "SYNOPSIS"
.nf
.B #include <infiniband/verbs_exp.h>
.BI "static inline struct ibv_exp_res_domain *ibv_exp_create_res_domain(struct ibv_context " "*context",
.BI "                                                                   struct ibv_exp_res_domain_init_attr " "*attr" ");"

.BI "static inline int ibv_exp_destroy_res_domain(struct ibv_context " "*context,"
.BI "                                             struct ibv_exp_res_domain " "*res_dom,"
.BI "                                             struct ibv_exp_destroy_res_domain_attr " "*attr" ");"
.fi
.SH "DESCRIPTION"
.B ibv_exp_create_res_domain()
Creates resource domain which is a verb object that may be associated with QP and a CQ objects on creation to enhance data-path performance.
.PP
The argument
.I attr
is an ibv_exp_res_domain_init_attr struct, as defined in <infiniband/verbs_exp.h>.
.PP
.nf
enum ibv_exp_thread_model {
        IBV_EXP_THREAD_SAFE,     /* The lib responsible to protect the object in multithreaded environment */
        IBV_EXP_THREAD_UNSAFE,   /* The application responsible to protect the object in multithreaded environment */
        IBV_EXP_THREAD_SINGLE    /* The object is called from only one thread */
};

enum ibv_exp_msg_model {
        IBV_EXP_MSG_DEFAULT,            /* Use the provider default message model */
        IBV_EXP_MSG_LOW_LATENCY,        /* Hint the provider to optimize for low latency */
        IBV_EXP_MSG_HIGH_BW,            /* Hint the provider to optimize for high bandwidth */
        IBV_EXP_MSG_FORCE_LOW_LATENCY,  /* Force the provider to optimize for low latency */
};

enum ibv_exp_res_domain_init_attr_comp_mask {
        IBV_EXP_RES_DOMAIN_THREAD_MODEL  = (1 << 0),
        IBV_EXP_RES_DOMAIN_MSG_MODEL     = (1 << 1),
        IBV_EXP_RES_DOMAIN_RESERVED      = (1 << 2),
};

struct ibv_exp_res_domain_init_attr {
        uint32_t                   comp_mask; /* use ibv_exp_res_domain_init_attr_comp_mask */
        enum ibv_exp_thread_model  thread_model;
        enum ibv_exp_msg_model     msg_model;
};

.PP
.B ibv_exp_destroy_res_domain()
Destroys the resource domain.

.SH "RETURN VALUE"
.B ibv_exp_create_res_domain()
returns a pointer to the created resource domain, or NULL if the request fails.

.PP
.B ibv_exp_destroy_res_domain()
returns 0 on success, or the value of errno on failure (which indicates the failure reason).

.SH "NOTES"

.SH "SEE ALSO"
.SH "AUTHORS"
.TP
Moshe Lazer <moshel@mellanox.com>
